import dbConnect from '@/lib/dbConnect'
import ProductCard from './ProductCard';

export const metadata = {
    title: "Products | NextStore",
    description: "Generated by create next app",
};

export default async function AllProducts() {

    const res = await fetch("https://next-store-gamma-eight.vercel.app/api/products", {
        cache: "no-store",
    });
    const products = await res.json();

    return (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 max-w-7xl mx-auto">
            {products?.map(product => (
                <ProductCard key={product._id} product={product} />
            ))}
        </div>
    )
}
